"""Bounded-label API metrics."""

from prometheus_client import Counter, Gauge, Histogram

REQUESTS = Counter(
    "commerce_demo_api_requests_total",
    "API requests",
    ("route_template", "method", "status_class"),
)
REQUEST_DURATION = Histogram(
    "commerce_demo_api_request_duration_seconds",
    "API request duration",
    ("route_template", "method"),
)
RUNS = Counter(
    "commerce_demo_runs_total", "Terminal runs", ("scenario", "terminal_status")
)
ACTIVE_RUNS = Gauge("commerce_demo_active_runs", "Active runs")
RUN_DURATION = Histogram(
    "commerce_demo_run_duration_seconds",
    "Run duration",
    ("scenario", "terminal_status"),
)
SSE_CONNECTIONS = Gauge("commerce_demo_sse_connections", "SSE connections")
EVENTS_REQUESTED = Counter(
    "commerce_demo_scenario_events_requested_total",
    "Requested scenario events",
    ("scenario",),
)
GENERATOR_STAGE_DURATION = Histogram(
    "commerce_demo_generator_stage_duration_seconds",
    "In-process scenario generator stage duration.",
    ("stage",),
)
GENERATOR_GENERATION_DURATION = Histogram(
    "commerce_demo_generator_generation_duration_seconds",
    "In-process scenario generation duration.",
    ("phase",),
)
GENERATOR_EVENTS_GENERATED = Counter(
    "commerce_demo_generator_events_generated_total",
    "Events generated by the in-process scenario generator.",
    ("scenario",),
)
GENERATOR_INTER_EVENT_INTERVAL = Histogram(
    "commerce_demo_generator_inter_event_interval_seconds",
    "Elapsed monotonic time between generated events.",
)
GENERATOR_SCHEDULER_DRIFT = Histogram(
    "commerce_demo_generator_scheduler_drift_seconds",
    "Positive lateness relative to the generator deadline.",
)
GENERATOR_MISSED_DEADLINES = Counter(
    "commerce_demo_generator_missed_deadlines_total",
    "Generator deadlines missed because event work exceeded the schedule.",
    ("scenario",),
)
REPOSITORY_CONNECTION_DURATION = Histogram(
    "commerce_demo_repository_connection_duration_seconds",
    "PostgreSQL connection establishment duration for the demo repository.",
)
